### ISSUE TITLE
Running unit tests on Travis

### ISSUE THREAD

**Issue by EduardoCopat** [abapGit/Test-Objects#4]
I didn't want to pollute abapGit with more issues and this is food for thought.

I wonder if it is possible to somehow run the unit tests on Travis. In other languages it is way easier, you just need to get the runtime and run the tests. In ABAP, that's virtually impossible since we would need somehow a complete netweaver solution.

How cool it would be to have an abap project which uses abapGit, then has static checks with abapLint, and then go through a continuous delivery pipeline?

Any ideas on this?

**Comment by larshp** [comment]
There are a few ways to approach the issue:

1: assuming someone has access to a Netweaver system, setup a githu webhook which triggers the ABAP system to download the latest code from git(via abapGit background mode, see https://github.com/larshp/abapGit/issues/244). And then run the unit tests and upload the results back. I think this would work for internal/private projects, but not for open source as someone might do a "DELETE FROM USR01." or similar in the code that is being tested.

2: build a ABAP virtual machine from scratch, it is in my backlog 😄

**Comment by EduardoCopat** [comment]
1. Yes, if you already have a SAP system running, you could indeed do that, it is feasible.

2. I was searching on the last weeks for this, but I couldn't find anything. I know that AWS can instantiate a netweaver VM (https://aws.amazon.com/sap/solutions/suite/), but couldn't find an open source version. If such thing as a ABAP Virtual Machine would exist, we could really use abapGit for parallel development and make use of the Github flow.

**Comment by larshp** [comment]
2: AWS just raises a question about licences and cost. Cool thing about travis is that it is free.

In my opinion we just need to build it, I've already spent quite some time moving in that direction, see https://larshp.github.io/abaplint/viz/. And hopefully once it exists then SAP will release the real thing, which will be much much better.

**Comment by sbcgua** [comment]
In fact there is this netweaver dev edition - https://blogs.sap.com/2016/11/03/sap-nw-as-abap-750-sp02-developer-edition-to-download/

I'm not sure about licensing of course (if it is positioned as an open service finally).
Also there is just pure basis, no ERP stuff
And ... much work to do to clear env each time ... 
But theoretically possible. Amazon or digital ocean or hetzner as a infrastructure platform - whichever is cheaper.

**Comment by EduardoCopat** [comment]
@sbcgua I was looking for that link. I downloaded this recently, but was rather disappointed that you need  50GB on my SSD. No space for that.

Unless we could run this on a docker container?

**Comment by sbcgua** [comment]
digitalocean 4GB + 60GB SSD costs just $40. Docker ... hmm ... could be convenient to deploy. Maybe worth to try someday :)

**Comment by larshp** [comment]
closing, no progress so far
